name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.ox }}
    strategy:
      matrix:
        os: [ubuntu-latest,ubuntu-24.04]
    steps:
      - name: echo a string 
        run: echo "hello world"
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l      
